import dayjs from "dayjs";
import RelativeTime from "dayjs/plugin/relativeTime";
import "dayjs/locale/zh-cn";
import { useAppearance, useMousePosition } from "./utils/stores.ts";
import { setLocale } from "yup";
import { getYupLocale } from "./utils/yup.ts";
import "./assets/css/style.scss";
import { isDragging } from "./utils/upload.ts";

export { default as Button } from "./components/button/Button.vue";
export { default as ButtonGroup } from "./components/button/ButtonGroup.vue";
export { default as SplitButton } from "./components/button/SplitButton.vue";
export { default as CodeEditor } from "./components/editor/CodeEditor.vue";
export { default as AutoComplete } from "./components/form/entries/AutoComplete.vue";
export { default as Calendar } from "./components/form/entries/Calendar.vue";
export { default as Checkbox } from "./components/form/entries/Checkbox.vue";
export { default as Combobox } from "./components/form/entries/Combobox.vue";
export { default as DatePicker } from "./components/form/entries/DatePicker.vue";
export { default as InputNumber } from "./components/form/entries/InputNumber.vue";
export { default as InputText } from "./components/form/entries/InputText.vue";
export { default as RadioGroup } from "./components/form/entries/RadioGroup.vue";
export { default as Segmented } from "./components/form/entries/Segmented.vue";
export { default as Select } from "./components/form/entries/Select.vue";
export { default as Slider } from "./components/form/entries/Slider.vue";
export { default as Switch } from "./components/form/entries/Switch.vue";
export { default as Textarea } from "./components/form/entries/Textarea.vue";
export { default as TimePicker } from "./components/form/entries/TimePicker.vue";
export { default as Transfer } from "./components/form/entries/Transfer.vue";
export { default as TreeSelect } from "./components/form/entries/TreeSelect.vue";
export { default as Avatar } from "./components/misc/Avatar.vue";
export { default as Background } from "./components/misc/Background.vue";
export { default as Badge } from "./components/misc/Badge.vue";
export { default as CopyableText } from "./components/misc/CopyableText.vue";
export { default as Code } from "./components/misc/Code.vue";
export { default as DataTable } from "./components/misc/DataTable.vue";
export { default as Divider } from "./components/misc/Divider.vue";
export { default as Empty } from "./components/misc/Empty.vue";
export { default as Kbd } from "./components/misc/Kbd.vue";
export { default as Message } from "./components/misc/Message.vue";
export { default as MeterGroup } from "./components/misc/MeterGroup.vue";
export { default as PageHeader } from "./components/misc/PageHeader.vue";
export { default as Result } from "./components/misc/Result.vue";
export { default as Skeleton } from "./components/misc/Skeleton.vue";
export { default as Table } from "./components/misc/Table.vue";
export { default as Tag } from "./components/misc/Tag.vue";
export { default as Breadcrumbs } from "./components/navigation/Breadcrumbs.vue";
export { default as ItemsPagination } from "./components/navigation/ItemsPagination.vue";
export { default as NavTabs } from "./components/navigation/NavTabs.vue";
export { default as Pagination } from "./components/navigation/Pagination.vue";
export { default as Sidebar } from "./components/navigation/Sidebar.vue";
export { default as Steps } from "./components/navigation/Steps.vue";
export { default as Tree } from "./components/navigation/Tree.vue";
export { default as Card } from "./components/panel/Card.vue";
export { default as Accordion } from "./components/panel/accordion/Accordion.vue";
export { default as AccordionPanel } from "./components/panel/accordion/AccordionPanel.vue";
export { default as CollapsablePanel } from "./components/panel/CollapsablePanel.vue";
export { default as CollapsiblePanel } from "./components/panel/CollapsablePanel.vue";
export { default as Panel } from "./components/panel/Panel.vue";
export { default as Contextmenu } from "./components/overlay/Contextmenu.vue";
export { default as ContextmenuOverlay } from "./components/overlay/ContextmenuOverlay.vue";
export { default as ConfirmDialog } from "./components/overlay/ConfirmDialog.vue";
export { default as Drawer } from "./components/overlay/Drawer.vue";
export { default as DropdownMenu } from "./components/overlay/DropdownMenu.vue";
export { default as Modal } from "./components/overlay/Modal.vue";
export { default as Popover } from "./components/overlay/Popover.vue";
export { default as Tooltip } from "./components/overlay/Tooltip.vue";
export { default as NotificationOverlay } from "./components/overlay/notification/NotificationOverlay.vue";
export { default as NotificationTemplate } from "./components/overlay/notification/NotificationTemplate.vue";
export { default as ProgressBar } from "./components/progress/ProgressBar.vue";
export { default as Spinner } from "./components/progress/Spinner.vue";
export { default as FileDropper } from "./components/upload/FileDropper.vue";
export { default as FileInfo } from "./components/upload/FileInfo.vue";
export { default as RButton } from "./components/button/Button.vue";
export { default as RButtonGroup } from "./components/button/ButtonGroup.vue";
export { default as RSplitButton } from "./components/button/SplitButton.vue";
export { default as RCodeEditor } from "./components/editor/CodeEditor.vue";
export { default as RAutoComplete } from "./components/form/entries/AutoComplete.vue";
export { default as RCalendar } from "./components/form/entries/Calendar.vue";
export { default as RCheckbox } from "./components/form/entries/Checkbox.vue";
export { default as RCombobox } from "./components/form/entries/Combobox.vue";
export { default as RDatePicker } from "./components/form/entries/DatePicker.vue";
export { default as RInputNumber } from "./components/form/entries/InputNumber.vue";
export { default as RInputText } from "./components/form/entries/InputText.vue";
export { default as RRadioGroup } from "./components/form/entries/RadioGroup.vue";
export { default as RSegmented } from "./components/form/entries/Segmented.vue";
export { default as RSelect } from "./components/form/entries/Select.vue";
export { default as RSlider } from "./components/form/entries/Slider.vue";
export { default as RSwitch } from "./components/form/entries/Switch.vue";
export { default as RTextarea } from "./components/form/entries/Textarea.vue";
export { default as RTimePicker } from "./components/form/entries/TimePicker.vue";
export { default as RTransfer } from "./components/form/entries/Transfer.vue";
export { default as RTreeSelect } from "./components/form/entries/TreeSelect.vue";
export { default as RAvatar } from "./components/misc/Avatar.vue";
export { default as RBackground } from "./components/misc/Background.vue";
export { default as RBadge } from "./components/misc/Badge.vue";
export { default as RCopyableText } from "./components/misc/CopyableText.vue";
export { default as RCode } from "./components/misc/Code.vue";
export { default as RDataTable } from "./components/misc/DataTable.vue";
export { default as RDivider } from "./components/misc/Divider.vue";
export { default as RElement } from "./components/misc/Element.vue";
export { default as REmpty } from "./components/misc/Empty.vue";
export { default as RKbd } from "./components/misc/Kbd.vue";
export { default as RMessage } from "./components/misc/Message.vue";
export { default as RMeterGroup } from "./components/misc/MeterGroup.vue";
export { default as RPageHeader } from "./components/misc/PageHeader.vue";
export { default as RResult } from "./components/misc/Result.vue";
export { default as RSkeleton } from "./components/misc/Skeleton.vue";
export { default as RTable } from "./components/misc/Table.vue";
export { default as RTag } from "./components/misc/Tag.vue";
export { default as RBreadcrumbs } from "./components/navigation/Breadcrumbs.vue";
export { default as RItemsPagination } from "./components/navigation/ItemsPagination.vue";
export { default as RNavTabs } from "./components/navigation/NavTabs.vue";
export { default as RPagination } from "./components/navigation/Pagination.vue";
export { default as RSidebar } from "./components/navigation/Sidebar.vue";
export { default as RSteps } from "./components/navigation/Steps.vue";
export { default as RTree } from "./components/navigation/Tree.vue";
export { default as RCard } from "./components/panel/Card.vue";
export { default as RAccordion } from "./components/panel/accordion/Accordion.vue";
export { default as RAccordionPanel } from "./components/panel/accordion/AccordionPanel.vue";
export { default as RCollapsablePanel } from "./components/panel/CollapsablePanel.vue";
export { default as RCollapsiblePanel } from "./components/panel/CollapsablePanel.vue";
export { default as RPanel } from "./components/panel/Panel.vue";
export { default as RContextmenu } from "./components/overlay/Contextmenu.vue";
export { default as RContextmenuOverlay } from "./components/overlay/ContextmenuOverlay.vue";
export { default as RConfirmDialog } from "./components/overlay/ConfirmDialog.vue";
export { default as RDrawer } from "./components/overlay/Drawer.vue";
export { default as RDropdownMenu } from "./components/overlay/DropdownMenu.vue";
export { default as RModal } from "./components/overlay/Modal.vue";
export { default as RPopover } from "./components/overlay/Popover.vue";
export { default as RTooltip } from "./components/overlay/Tooltip.vue";
export { default as RNotificationOverlay } from "./components/overlay/notification/NotificationOverlay.vue";
export { default as RNotificationTemplate } from "./components/overlay/notification/NotificationTemplate.vue";
export { default as RProgressBar } from "./components/progress/ProgressBar.vue";
export { default as RSpinner } from "./components/progress/Spinner.vue";
export { default as RFileDropper } from "./components/upload/FileDropper.vue";
export { default as RFileInfo } from "./components/upload/FileInfo.vue";
export { default as MButton } from "./components/button/Button.vue";
export { default as MButtonGroup } from "./components/button/ButtonGroup.vue";
export { default as MSplitButton } from "./components/button/SplitButton.vue";
export { default as MCodeEditor } from "./components/editor/CodeEditor.vue";
export { default as MAutoComplete } from "./components/form/entries/AutoComplete.vue";
export { default as MCalendar } from "./components/form/entries/Calendar.vue";
export { default as MCheckbox } from "./components/form/entries/Checkbox.vue";
export { default as MCombobox } from "./components/form/entries/Combobox.vue";
export { default as MDatePicker } from "./components/form/entries/DatePicker.vue";
export { default as MInputNumber } from "./components/form/entries/InputNumber.vue";
export { default as MInputText } from "./components/form/entries/InputText.vue";
export { default as MRadioGroup } from "./components/form/entries/RadioGroup.vue";
export { default as MSegmented } from "./components/form/entries/Segmented.vue";
export { default as MSelect } from "./components/form/entries/Select.vue";
export { default as MSlider } from "./components/form/entries/Slider.vue";
export { default as MSwitch } from "./components/form/entries/Switch.vue";
export { default as MTextarea } from "./components/form/entries/Textarea.vue";
export { default as MTimePicker } from "./components/form/entries/TimePicker.vue";
export { default as MTransfer } from "./components/form/entries/Transfer.vue";
export { default as MTreeSelect } from "./components/form/entries/TreeSelect.vue";
export { default as MAvatar } from "./components/misc/Avatar.vue";
export { default as MBackground } from "./components/misc/Background.vue";
export { default as MBadge } from "./components/misc/Badge.vue";
export { default as MCopyableText } from "./components/misc/CopyableText.vue";
export { default as MCode } from "./components/misc/Code.vue";
export { default as MDataTable } from "./components/misc/DataTable.vue";
export { default as MDivider } from "./components/misc/Divider.vue";
export { default as MElement } from "./components/misc/Element.vue";
export { default as MEmpty } from "./components/misc/Empty.vue";
export { default as MKbd } from "./components/misc/Kbd.vue";
export { default as MMessage } from "./components/misc/Message.vue";
export { default as MMeterGroup } from "./components/misc/MeterGroup.vue";
export { default as MPageHeader } from "./components/misc/PageHeader.vue";
export { default as MResult } from "./components/misc/Result.vue";
export { default as MSkeleton } from "./components/misc/Skeleton.vue";
export { default as MTable } from "./components/misc/Table.vue";
export { default as MTag } from "./components/misc/Tag.vue";
export { default as MBreadcrumbs } from "./components/navigation/Breadcrumbs.vue";
export { default as MItemsPagination } from "./components/navigation/ItemsPagination.vue";
export { default as MNavTabs } from "./components/navigation/NavTabs.vue";
export { default as MPagination } from "./components/navigation/Pagination.vue";
export { default as MSidebar } from "./components/navigation/Sidebar.vue";
export { default as MSteps } from "./components/navigation/Steps.vue";
export { default as MTree } from "./components/navigation/Tree.vue";
export { default as MCard } from "./components/panel/Card.vue";
export { default as MAccordion } from "./components/panel/accordion/Accordion.vue";
export { default as MAccordionPanel } from "./components/panel/accordion/AccordionPanel.vue";
export { default as MCollapsablePanel } from "./components/panel/CollapsablePanel.vue";
export { default as MCollapsiblePanel } from "./components/panel/CollapsablePanel.vue";
export { default as MPanel } from "./components/panel/Panel.vue";
export { default as MContextmenu } from "./components/overlay/Contextmenu.vue";
export { default as MContextmenuOverlay } from "./components/overlay/ContextmenuOverlay.vue";
export { default as MConfirmDialog } from "./components/overlay/ConfirmDialog.vue";
export { default as MDrawer } from "./components/overlay/Drawer.vue";
export { default as MDropdownMenu } from "./components/overlay/DropdownMenu.vue";
export { default as MModal } from "./components/overlay/Modal.vue";
export { default as MPopover } from "./components/overlay/Popover.vue";
export { default as MTooltip } from "./components/overlay/Tooltip.vue";
export { default as MNotificationOverlay } from "./components/overlay/notification/NotificationOverlay.vue";
export { default as MNotificationTemplate } from "./components/overlay/notification/NotificationTemplate.vue";
export { default as MProgressBar } from "./components/progress/ProgressBar.vue";
export { default as MSpinner } from "./components/progress/Spinner.vue";
export { default as MFileDropper } from "./components/upload/FileDropper.vue";
export { default as MFileInfo } from "./components/upload/FileInfo.vue";
export { useAppearance, useLocale, useMousePosition, useScreenWidth } from "./utils/stores.ts";
export {
  requestNotifPermission,
  setSystemNotif,
  setSystemNotificationsEnabled,
  systemNotificationsEnabled,
} from "./utils/notifications.ts";
export { useThemeVars } from "./utils/theme.ts";
export type { Locale, Rendering, Theme, ThemeTransition } from "./utils/stores.ts";
export type {
  NotificationType,
  RetaNotifSettings,
  SystemNotifSettings,
} from "./utils/notifications.ts";
export type { ThemeVarName, ThemeVars } from "./utils/theme.ts";
export type { TreeNode } from "./utils/tree.ts";

dayjs.extend(RelativeTime);
dayjs.locale("zh-cn");

export async function loadUi() {
  setLocale(getYupLocale());
  useAppearance().load();
  window.removeEventListener("mousemove", useMousePosition().onMouseMove);
  window.removeEventListener("mouseout", useMousePosition().onMouseOut);
  window.addEventListener("mousemove", useMousePosition().onMouseMove);
  window.addEventListener("mouseout", useMousePosition().onMouseOut);

  let dragTimeout = -1;

  window.addEventListener("dragover", () => {
    clearTimeout(dragTimeout);
    isDragging.value = true;
  });

  window.addEventListener("dragleave", () => {
    clearTimeout(dragTimeout);
    dragTimeout = window.setTimeout(() => {
      isDragging.value = false;
    }, 100);
  });

  window.addEventListener("drop", () => {
    isDragging.value = false;
    clearTimeout(dragTimeout);
  });

  window.addEventListener("blur", () => {
    isDragging.value = false;
    clearTimeout(dragTimeout);
  });
}
